stages:
  - build
  - deploy

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/e-commerce

deploy:
  stage: deploy
  image: node:18
  script:
    - echo "Desplegando aplicación..."
    - npm install -g @angular/cli@16.2.16
    - npm run build
    # - npm run deploy
  only:
    - main