image: node:20

stages:
  - build
  - deploy

before_script:
  - npm install -g @angular/cli

build:
  stage: build
  script:
    - npm install
    - ng build
  artifacts:
    paths:
      - dist/e-commerce
  only:
    - main

deploy:
  stage: deploy
  script:
    - mv dist/e-commerce public  # Mueve los archivos generados a la carpeta 'public'
  only:
    - main
