stages:
  - build
  - deploy

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  image: node:18
  script:
    - echo "Desplegando aplicación..."
    - npm install
    - ng build
    # - npm run deploy
  only:
    - main